"""Build only (never upload) a normal ELRS image with optional runtime chat."""
import argparse
import json
import os
import re
from pathlib import Path
import shutil
import subprocess
import sys
from inspect_image import metadata
from source_digest import firmware_digest

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'src'
FAMILIES = [(m, r) for m in ('ESP32', 'ESP32S3', 'ESP32C3', 'ESP8285')
            for r in ('2400', '900', 'LR1121') if not (m == 'ESP8285' and r == 'LR1121')]
POWERS = [10, 25, 50, 100, 250, 500, 1000, 2000]

def make_targets():
    blocks = ['; Generated by tools/build_chat.py. No upload targets are used.\n']
    for m, r in FAMILIES:
        base = f'Unified_{m}_{r}_TX_via_UART'
        blocks.append(f'''[env:Unified_{m}_{r}_TX_CHAT]
extends = env:{base}
build_flags =
    ${{env:{base}.build_flags}}
    ${{chat_options.build_flags}}
    -DELRS_CHAT=1
''')
    (SRC / 'targets/chat.ini').write_text('\n'.join(blocks), encoding='utf-8')

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--mcu', choices=sorted({m for m, _ in FAMILIES}), default='ESP32')
    parser.add_argument('--radio', choices=['2400', '900', 'LR1121'], default='2400')
    parser.add_argument('--frequency', type=int, default=0, help='Default chat Hz; 0 leaves it unprovisioned. Lua configuration requires --experimental-rf. Ordinary RC remains enabled.')
    parser.add_argument('--power-mw', type=int, choices=POWERS, default=10)
    parser.add_argument('--board', help='Exact key in ELRS hardware/targets.json (manufacturer.tx_2400.product, etc.)')
    parser.add_argument('--list-boards', action='store_true', help='List board keys for the selected MCU/radio family')
    parser.add_argument('--domain', choices=['FCC_915','AU_915','EU_868','IN_866'],
                        help='Upstream sub-GHz calibration/domain setting; does not certify this chat protocol')
    parser.add_argument('--configure-only', action='store_true')
    parser.add_argument('--experimental-rf', action='store_true',
                        help='Opt in to the unqualified fixed-channel RF profile; not a regulatory approval')
    args = parser.parse_args()
    if (args.mcu, args.radio) not in FAMILIES:
        parser.error('Unsupported MCU/radio combination')
    if args.frequency:
        if not args.experimental_rf:
            parser.error('Nonzero chat frequency requires --experimental-rf; stock RF domains do not qualify the new waveform')
        valid_24 = 2401000000 <= args.frequency <= 2482000000
        valid_900 = 863000000 <= args.frequency <= 928000000
        if not ((args.radio in ('2400', 'LR1121') and valid_24) or
                (args.radio in ('900', 'LR1121') and valid_900)):
            parser.error('Frequency outside this adapter\'s implemented range')
    if args.radio != '2400' and not args.domain and not args.list_boards:
        parser.error('Specify --domain: ordinary RC uses this region even when chat frequency is 0')
    base = f'Unified_{args.mcu}_{args.radio}_TX'
    if args.list_boards:
        database = SRC/'hardware/targets.json'
        if not database.exists(): parser.error('Run tools/prepare_chat.py first')
        for vendor, groups in json.loads(database.read_text()).items():
            for group, products in groups.items():
                if not isinstance(products,dict): continue
                for key, entry in products.items():
                    if isinstance(entry,dict) and entry.get('firmware')==base:
                        print(f'{vendor}.{group}.{key}: {entry["product_name"]}')
        return
    if args.board:
        database = SRC / 'hardware/targets.json'
        if not database.is_file():
            parser.error('Run tools/prepare_chat.py first to fetch hardware definitions')
        entry = json.loads(database.read_text())
        try:
            for key in args.board.split('.'):
                entry = entry[key]
        except (KeyError, TypeError):
            parser.error('Unknown board key')
        if entry.get('firmware') != base:
            parser.error(f'Board requires {entry.get("firmware")}, not {base}')
        version = re.match(r'(\d+)\.(\d+)\.(\d+)',entry.get('min_version','0.0.0'))
        if not version: parser.error('Board has an unrecognized minimum version')
        minimum = tuple(map(int,version.groups()))
        if minimum > (4,1,0):
            parser.error('This board requires a newer ELRS base than the pinned 4.1.0')
        layout = json.loads((SRC / 'hardware/TX' / entry['layout_file']).read_text())
        layout.update(entry.get('overlay', {}))
        if layout.get('radio_nss_2', -1) != -1:
            parser.error('Dual RF/Gemini hardware is not supported by v1')
        if not layout.get('power_min',0) <= POWERS.index(args.power_mw) <= layout.get('power_max',-1):
            parser.error('Requested power is outside this board\'s calibrated range')
    make_targets()
    # A development overlay, leaving the stock project and its CI unchanged.
    project = (SRC/'platformio.ini').read_text(encoding='utf-8')
    project = project.replace('\ttargets/esp8285-rx.ini',
                              '\ttargets/esp8285-rx.ini\n\ttargets/chat.ini\n\tchat_options.ini')
    (SRC/'chat-platformio.ini').write_text(project,encoding='utf-8')
    env_name = base + '_CHAT'
    ini = f'''[chat_options]
build_flags =
    -DCHAT_FREQUENCY_HZ={args.frequency}UL
    -DCHAT_POWER={POWERS.index(args.power_mw)}
'''
    if args.experimental_rf:
        ini += '    -DCHAT_EXPERIMENTAL_RF=1\n'
    if args.radio != '2400':
        ini += f'    -DRegulatory_Domain_{args.domain}\n'
    if args.board:
        ini += f'\n[env:{env_name}]\nboard_config = {args.board}\n'
    (SRC / 'chat_options.ini').write_text(ini, encoding='utf-8')
    if args.configure_only:
        return
    pio = shutil.which('pio') or shutil.which('platformio')
    if not pio:
        parser.error('Install PlatformIO Core: python -m pip install platformio')
    env = dict(os.environ)
    source_hash = firmware_digest()
    # A pipe is reliably non-interactive; Windows NUL may report isatty=True
    # and send upstream's bare-image configuration into an EOF prompt.
    result = subprocess.run([pio, 'run', '-d', str(SRC), '-c', str(SRC/'chat-platformio.ini'), '-e', env_name], env=env, input=b'')
    if result.returncode:
        raise SystemExit(result.returncode)
    if firmware_digest() != source_hash:
        raise SystemExit('Firmware sources changed during the build; rebuild before exporting')
    output = ROOT / 'dist' / env_name
    # Different internal modules can share one Unified environment but have
    # different PA calibration/fan pins. Keep their flash images separate.
    if args.board:
        output = output / args.board
    output.mkdir(parents=True, exist_ok=True)
    image_info = metadata(SRC / '.pio/build' / env_name / 'firmware.bin')
    if image_info.get('metadata_bytes',0) < 2704:
        raise SystemExit('Build lacks required Unified configuration; refusing to export')
    if args.board and image_info.get('hardware') != layout:
        raise SystemExit('Embedded hardware does not match requested board; refusing to export')
    for name in ('firmware.bin', 'bootloader.bin', 'partitions.bin', 'boot_app0.bin'):
        source = SRC / '.pio/build' / env_name / name
        if source.exists():
            shutil.copy2(source, output / name)
    manifest = dict(vars(args), environment=env_name, hardware_embedded=bool(args.board),
                    chat_rf_enabled=bool(args.experimental_rf), normal_rc_enabled=True,
                    integration='runtime-v3', local_protocol=2, local_transport='crsf-string-parameter-v1', rf_protocol=1,
                    upstream='a9d4a9cb5b5687c4c9d7e9e7fbdf44ad93651da6',
                    warning='No hardware/RF validation has been performed. A bare image has no module pinout.')
    manifest['hardware_revision'] = subprocess.check_output(
        ['git','rev-parse','HEAD'],cwd=SRC/'hardware',text=True).strip()
    manifest['source_sha256'] = source_hash
    manifest['fork_commit'] = subprocess.check_output(['git','rev-parse','HEAD'], cwd=ROOT, text=True).strip()
    manifest['lua_profile_configuration'] = True
    manifest['image'] = image_info
    (output / 'build.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
    print(f'Build saved: {output}')
    if not args.board:
        print('BARE DEVELOPMENT IMAGE: no module pinout. Do not flash this file to an arbitrary module.')

if __name__ == '__main__':
    main()
